;METADATA=(Diff=true, UseCommands=true)
[ServerSettings]
ShowMapPlayerLocation=True
AllowThirdPersonPlayer=True
ServerCrosshair=True
RCONPort=27020
TheMaxStructuresInRange=10500
StartTimeHour=-1
OxygenSwimSpeedStatMultiplier=1
StructurePreventResourceRadiusMultiplier=1
TribeNameChangeCooldown=15
PlatformSaddleBuildAreaBoundsMultiplier=1
AlwaysAllowStructurePickup=True
StructurePickupTimeAfterPlacement=30
StructurePickupHoldDuration=0.5
AllowHideDamageSourceFromLogs=True
RaidDinoCharacterFoodDrainMultiplier=1
PvEDinoDecayPeriodMultiplier=1
KickIdlePlayersPeriod=3600
PerPlatformMaxStructuresMultiplier=1
AutoSavePeriodMinutes=15
MaxTamedDinos=5000
MaxTamedDinos_SoftTameLimit=5000
MaxTamedDinos_SoftTameLimit_CountdownForDeletionDuration=604800
OverrideSecondsUntilBuriedTreasureAutoReveals=1209600
ItemStackSizeMultiplier=1
RCONServerGameLogBuffer=600
ImplantSuicideCD=28800
AllowHitMarkers=True
ForceGachaUnhappyInCaves=True
LimitBunkersPerTribe=True
LimitBunkersPerTribeNum=3
AllowRidingDinosInsideBunkers=True
AllowDinoAIInsideBunkers=True
MinDistanceBetweenBunkers=3000
EnemyAccessBunkerHPThreshold=0.25
BunkerUnderHPThresholdDmgMultiplier=0.0500000007
CryoHospitalHoursToRegenHP=1
CryoHospitalHoursToRegenFood=24
CryoHospitalHoursToDrainTorpor=1
CryoHospitalMatingCooldownReduction=2
BloodforgeReinforceExtraDurability=0.300000012
BloodforgeReinforceResourceCostMultiplier=3
BloodforgeReinforceSpeedMultiplier=0.100000001
RCONEnabled=True
ServerAdminPassword=itsnotyokan

[SessionSettings]
SessionName=Yokan Ark The Center

[/Script/Engine.GameSession]
MaxPlayers=10

